### ISSUE TITLE
it's so cool !

### ISSUE THREAD

**Issue by deepred5** [yui540/DropOut#26]
The website looks like a  MAD ! I had thought of making a [MAD](https://www.bilibili.com/video/av5263072?from=search&seid=12331257051159563171) (the [demo](http://deepred5.com/amagami/)) by using css animation just like you, but finally I gave up the idea. You did it !

**Comment by idea100** [comment]
yes, it's so cool, @deepred5 ,

**Comment by yuki540net** [comment]
Thank you!
